# Generated by Django 5.0.6 on 2024-05-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asnwer',
            new_name='Answer',
        ),
    ]
